name: Allure
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    paths:
      - '**.json'
    branches-ignore:
      - release/**
jobs:
  Allure:
    runs-on: ubuntu-latest
    name: Generate Allure report
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Install Allure
        run: |
          curl -o allure-2.22.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.22.1/allure-commandline-2.22.1.tgz
          sudo tar -zxvf allure-2.22.1.tgz -C .
          sudo ln -s ./allure-2.22.1/bin/allure ./allure
          ./allure --version
      
      - name: Checkout git repository
        uses: actions/checkout@v3
        with:
          path: "./report/"
    
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: report
          path: "./docs/"

      - name: Get Allure reports history and prepare dirs
        run: |
          cp -R ./docs/history/ ./report/history || echo
          mkdir ./temp
          cp -R ./docs/.git/ ./temp/

      - name: Build Allure reports
        run: |
          ./allure generate ./report -o ./docs --clean
          cp -R ./temp/.git/ ./docs/

      - name: Commit static site to repository with GitHub Pages enabled
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "."
          cwd: "./docs/"
          message: Update Allure report
          push: "origin report --set-upstream --force"
      
      - name: ls -la
        run: ls -la && ls -la ./docs/

      - name: Close pull request and delete its branch
        run: gh pr close --comment "Allure report generated (auto closing PR)" --delete-branch "${{ github.event.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}