name: Allure
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    paths:
      - '**.json'
jobs:
  Allure:
    runs-on: ubuntu-latest
    name: Generate Allure report
    permissions:
      contents: write
    steps:
      - name: Install Allure
        run: |
          curl -o allure-2.22.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.22.1/allure-commandline-2.22.1.tgz
          sudo tar -zxvf allure-2.22.1.tgz -C .
          sudo ln -s ./allure-2.22.1/bin/allure ./allure
          ./allure --version

      - name: Checkout git repository
        uses: actions/checkout@v3
        with:
          path: report

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: report
          path: docs

      - name: Get Allure reports history
        run: cp -R ./docs/history/ ./report/history || echo
      
      - name: Build Allure reports
        run: ./allure generate ./report -o ./docs --clean
      
      - name: Commit static site to repository with GitHub Pages enabled
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          user-name: mkusz
          user-email: 9740637+mkusz@users.noreply.github.com
          source-directory: docs
          destination-github-username: mkusz
          destination-repository-name: test-sub
          target-branch: report
      
      - name: Close pull request
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "Allure report generated, pull request is closed"
      
      - name: Delete current branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          numbers: ${{ github.event.pull_request.number }}
      