name: Allure
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Allure:
    runs-on: ubuntu-latest
    name: Generate Allure report
    steps:
      - name: Install Allure
        run: |
          curl -o allure-2.22.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.22.1/allure-commandline-2.22.1.tgz
          sudo tar -zxvf allure-2.22.1.tgz -C .
          sudo ln -s ./allure-2.22.1/bin/allure ./allure
          ./allure --version
      - name: Checkout git repository
        uses: actions/checkout@v3
        with:
          path: report
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: report
          path: docs
      - name: Get Allure reports history
        run: cp -R ./docs/history/ ./report/history || echo
      
      - name: Build Allure reports
        run: ./allure generate ./report -o ./docs --clean
      
      - name: List files
        run: |
          ls -la
          ls -la ./report
          ls -la ./report/history
          ls -la ./docs
      
      - name: Commit static site to repository with GitHub Pages enabled
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          user-name: mkusz
          user-email: 9740637+mkusz@users.noreply.github.com
          source-directory: docs
          destination-github-username: mkusz
          destination-repository-name: test-sub
          target-branch: report
      
#       - name: Deploy report to Github Pages
#         if: always()
#         uses: peaceiris/actions-gh-pages@v2
#         env:
#           PERSONAL_TOKEN: ${{ secrets.API_TESTEREMBYC_PL_DEPLOY_TOKEN }}
#           PUBLISH_BRANCH: report
#           PUBLISH_DIR: history
#       - name: Post the link to the report
#         if: always()
#         uses: Sibz/github-status-action@v1
#         with: 
#             authToken: ${{secrets.GITHUB_TOKEN}}
#             context: 'Test report'
#             state: 'success'
#             sha: ${{ github.event.pull_request.head.sha }}
#             target_url: github.com/mkusz/test-sub/${{ github.run_number }}
    
