name: Allure
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    paths:
      - '**.json'
jobs:
  Allure:
    runs-on: ubuntu-latest
    name: Generate Allure report
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Install Allure
        run: |
          curl -o allure-2.22.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.22.1/allure-commandline-2.22.1.tgz
          sudo tar -zxvf allure-2.22.1.tgz -C .
          sudo ln -s ./allure-2.22.1/bin/allure ./allure
          ./allure --version
      
      - name: Checkout git repository
        uses: actions/checkout@v3
        with:
          path: "./report/"

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: report
          path: "./docs/"
      
      - name: Check report folder
        run: ls -al ./report/

      - name: Check docs folder
        run: ls -al ./docs/

      - name: Get Allure reports history
        run: cp -R ./docs/history/ ./report/history || echo
      
      - name: Build Allure reports
        run: ./allure generate ./report -o ./docs
      
      - name: Check report folder
        run: ls -al ./report/

      - name: Check docs folder
        run: ls -al ./docs/

      - name: Commit static site to repository with GitHub Pages enabled
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "."
          cwd: "./docs/"
          message: Update Allure report
          push: "origin report --set-upstream --force"
      
      - name: Close pull request and delete its branch
        uses: peter-evans/close-pull@v3
        with:
          comment: Allure report generated.
          delete-branch: true
      